### PR TITLE
 feat: add missing transforms #10

### PR DESCRIPTION
**Pull request by kjugi**
Moving from original PR: https://github.com/bjohansebas/codemod/pull/10

I have listed missing deprecated transforms to implement

 >   res.send(status, body) and res.send(body, status) signatures: Use res.status(status).send(body).

>    res.send(status) signature: Use res.sendStatus(status) for simple status responses, or res.status(status).send() for sending a status code with an optional body.

>    res.json(status, obj) and res.json(obj, status) signatures: Use res.status(status).json(obj).

>    res.jsonp(status, obj) and res.jsonp(obj, status) signatures: Use res.status(status).jsonp(obj).

Based on the article:
- https://expressjs.com/en/guide/migrating-5.html#res.send.body
- https://expressjs.com/en/guide/migrating-5.html#res.send.status
- https://expressjs.com/en/guide/migrating-5.html#res.json
- https://expressjs.com/en/guide/migrating-5.html#res.jsonp

Plus comparing the versions between v3 and v4-v5:

for json:
- https://expressjs.com/en/3x/api.html#res.json
- https://expressjs.com/en/4x/api.html#res.json and same parameters structure for v5 https://expressjs.com/en/5x/api.html#res.json

for jsonp:
- https://expressjs.com/en/3x/api.html#res.jsonp
- https://expressjs.com/en/4x/api.html#res.jsonp and same parameters structure for v5 https://expressjs.com/en/5x/api.html#res.jsonp

for send: 
- https://expressjs.com/en/3x/api.html#res.send
- https://expressjs.com/en/4x/api.html#res.send and the same parameters structure for v5 https://expressjs.com/en/5x/api.html#res.send

### CODE REVIEW

**Comment by kjugi** [comment]
@bjohansebas I will make a separate PR for `app.param(fn)`. This might require additional changes and I want to avoid making this PR too big.

**Comment by bjohansebas** [comment]
Why are you adding v3 to the file name? Can we just leave it without the v3, or is there another reason?

**Comment by kjugi** [comment]
Good call, @bjohansebas! From what I see, it's directly related to the syntax supported in v3. It was deprecated in v4.

Do we want to keep all transforms on the same level under `/transforms/`? For now, we haven't agreed on the structure so I have added a file prefix to keep it clear. All other transforms are related to changes between v4 and v5 (correct me if I'm wrong here).

I think it might require some separation to avoid going insane in the future.

**Comment by bjohansebas** [comment]
Although it was deprecated in v4, it still worked until it was finally removed in v5, so if we want to do this, it should be v4 instead of v3.

While writing this comment, I realized that we should only add it in this codemod, so it seems fine to me.

**Comment by kjugi** [comment]
I can rename it from v3 prefix to v4. We agreed to focus on v4 for now so all good.

We should create some agreement about it right after we have current part done.

**Review by bjohansebas — APPROVED** [review]
Great!

**Pull request merged**
